# Generated by Django 4.0.4 on 2022-05-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
